// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: wblog_msg_content.proto

package com.hugo.wblog.proto;

public final class WblogMsgProto {
  private WblogMsgProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface wblog_msgOrBuilder extends
      // @@protoc_insertion_point(interface_extends:wblog_msg)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>int64 id = 1;</code>
     */
    long getId();

    /**
     * <code>string msgSender = 2;</code>
     */
    java.lang.String getMsgSender();
    /**
     * <code>string msgSender = 2;</code>
     */
    com.google.protobuf.ByteString
        getMsgSenderBytes();

    /**
     * <code>string msgReceiver = 3;</code>
     */
    java.lang.String getMsgReceiver();
    /**
     * <code>string msgReceiver = 3;</code>
     */
    com.google.protobuf.ByteString
        getMsgReceiverBytes();

    /**
     * <code>string msgContent = 4;</code>
     */
    java.lang.String getMsgContent();
    /**
     * <code>string msgContent = 4;</code>
     */
    com.google.protobuf.ByteString
        getMsgContentBytes();

    /**
     * <code>int64 status = 5;</code>
     */
    long getStatus();

    /**
     * <code>.google.protobuf.Timestamp createDate = 6;</code>
     */
    boolean hasCreateDate();
    /**
     * <code>.google.protobuf.Timestamp createDate = 6;</code>
     */
    com.google.protobuf.Timestamp getCreateDate();
    /**
     * <code>.google.protobuf.Timestamp createDate = 6;</code>
     */
    com.google.protobuf.TimestampOrBuilder getCreateDateOrBuilder();
  }
  /**
   * Protobuf type {@code wblog_msg}
   */
  public  static final class wblog_msg extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:wblog_msg)
      wblog_msgOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use wblog_msg.newBuilder() to construct.
    private wblog_msg(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private wblog_msg() {
      msgSender_ = "";
      msgReceiver_ = "";
      msgContent_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new wblog_msg();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private wblog_msg(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {

              id_ = input.readInt64();
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              msgSender_ = s;
              break;
            }
            case 26: {
              java.lang.String s = input.readStringRequireUtf8();

              msgReceiver_ = s;
              break;
            }
            case 34: {
              java.lang.String s = input.readStringRequireUtf8();

              msgContent_ = s;
              break;
            }
            case 40: {

              status_ = input.readInt64();
              break;
            }
            case 50: {
              com.google.protobuf.Timestamp.Builder subBuilder = null;
              if (createDate_ != null) {
                subBuilder = createDate_.toBuilder();
              }
              createDate_ = input.readMessage(com.google.protobuf.Timestamp.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(createDate_);
                createDate_ = subBuilder.buildPartial();
              }

              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.hugo.wblog.proto.WblogMsgProto.internal_static_wblog_msg_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.hugo.wblog.proto.WblogMsgProto.internal_static_wblog_msg_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.hugo.wblog.proto.WblogMsgProto.wblog_msg.class, com.hugo.wblog.proto.WblogMsgProto.wblog_msg.Builder.class);
    }

    public static final int ID_FIELD_NUMBER = 1;
    private long id_;
    /**
     * <code>int64 id = 1;</code>
     */
    public long getId() {
      return id_;
    }

    public static final int MSGSENDER_FIELD_NUMBER = 2;
    private volatile java.lang.Object msgSender_;
    /**
     * <code>string msgSender = 2;</code>
     */
    public java.lang.String getMsgSender() {
      java.lang.Object ref = msgSender_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        msgSender_ = s;
        return s;
      }
    }
    /**
     * <code>string msgSender = 2;</code>
     */
    public com.google.protobuf.ByteString
        getMsgSenderBytes() {
      java.lang.Object ref = msgSender_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        msgSender_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int MSGRECEIVER_FIELD_NUMBER = 3;
    private volatile java.lang.Object msgReceiver_;
    /**
     * <code>string msgReceiver = 3;</code>
     */
    public java.lang.String getMsgReceiver() {
      java.lang.Object ref = msgReceiver_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        msgReceiver_ = s;
        return s;
      }
    }
    /**
     * <code>string msgReceiver = 3;</code>
     */
    public com.google.protobuf.ByteString
        getMsgReceiverBytes() {
      java.lang.Object ref = msgReceiver_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        msgReceiver_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int MSGCONTENT_FIELD_NUMBER = 4;
    private volatile java.lang.Object msgContent_;
    /**
     * <code>string msgContent = 4;</code>
     */
    public java.lang.String getMsgContent() {
      java.lang.Object ref = msgContent_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        msgContent_ = s;
        return s;
      }
    }
    /**
     * <code>string msgContent = 4;</code>
     */
    public com.google.protobuf.ByteString
        getMsgContentBytes() {
      java.lang.Object ref = msgContent_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        msgContent_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int STATUS_FIELD_NUMBER = 5;
    private long status_;
    /**
     * <code>int64 status = 5;</code>
     */
    public long getStatus() {
      return status_;
    }

    public static final int CREATEDATE_FIELD_NUMBER = 6;
    private com.google.protobuf.Timestamp createDate_;
    /**
     * <code>.google.protobuf.Timestamp createDate = 6;</code>
     */
    public boolean hasCreateDate() {
      return createDate_ != null;
    }
    /**
     * <code>.google.protobuf.Timestamp createDate = 6;</code>
     */
    public com.google.protobuf.Timestamp getCreateDate() {
      return createDate_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : createDate_;
    }
    /**
     * <code>.google.protobuf.Timestamp createDate = 6;</code>
     */
    public com.google.protobuf.TimestampOrBuilder getCreateDateOrBuilder() {
      return getCreateDate();
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (id_ != 0L) {
        output.writeInt64(1, id_);
      }
      if (!getMsgSenderBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, msgSender_);
      }
      if (!getMsgReceiverBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, msgReceiver_);
      }
      if (!getMsgContentBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 4, msgContent_);
      }
      if (status_ != 0L) {
        output.writeInt64(5, status_);
      }
      if (createDate_ != null) {
        output.writeMessage(6, getCreateDate());
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (id_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(1, id_);
      }
      if (!getMsgSenderBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, msgSender_);
      }
      if (!getMsgReceiverBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, msgReceiver_);
      }
      if (!getMsgContentBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, msgContent_);
      }
      if (status_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(5, status_);
      }
      if (createDate_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(6, getCreateDate());
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.hugo.wblog.proto.WblogMsgProto.wblog_msg)) {
        return super.equals(obj);
      }
      com.hugo.wblog.proto.WblogMsgProto.wblog_msg other = (com.hugo.wblog.proto.WblogMsgProto.wblog_msg) obj;

      if (getId()
          != other.getId()) return false;
      if (!getMsgSender()
          .equals(other.getMsgSender())) return false;
      if (!getMsgReceiver()
          .equals(other.getMsgReceiver())) return false;
      if (!getMsgContent()
          .equals(other.getMsgContent())) return false;
      if (getStatus()
          != other.getStatus()) return false;
      if (hasCreateDate() != other.hasCreateDate()) return false;
      if (hasCreateDate()) {
        if (!getCreateDate()
            .equals(other.getCreateDate())) return false;
      }
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + ID_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getId());
      hash = (37 * hash) + MSGSENDER_FIELD_NUMBER;
      hash = (53 * hash) + getMsgSender().hashCode();
      hash = (37 * hash) + MSGRECEIVER_FIELD_NUMBER;
      hash = (53 * hash) + getMsgReceiver().hashCode();
      hash = (37 * hash) + MSGCONTENT_FIELD_NUMBER;
      hash = (53 * hash) + getMsgContent().hashCode();
      hash = (37 * hash) + STATUS_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getStatus());
      if (hasCreateDate()) {
        hash = (37 * hash) + CREATEDATE_FIELD_NUMBER;
        hash = (53 * hash) + getCreateDate().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.hugo.wblog.proto.WblogMsgProto.wblog_msg parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.hugo.wblog.proto.WblogMsgProto.wblog_msg parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.hugo.wblog.proto.WblogMsgProto.wblog_msg parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.hugo.wblog.proto.WblogMsgProto.wblog_msg parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.hugo.wblog.proto.WblogMsgProto.wblog_msg parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.hugo.wblog.proto.WblogMsgProto.wblog_msg parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.hugo.wblog.proto.WblogMsgProto.wblog_msg parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.hugo.wblog.proto.WblogMsgProto.wblog_msg parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.hugo.wblog.proto.WblogMsgProto.wblog_msg parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.hugo.wblog.proto.WblogMsgProto.wblog_msg parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.hugo.wblog.proto.WblogMsgProto.wblog_msg parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.hugo.wblog.proto.WblogMsgProto.wblog_msg parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.hugo.wblog.proto.WblogMsgProto.wblog_msg prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code wblog_msg}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:wblog_msg)
        com.hugo.wblog.proto.WblogMsgProto.wblog_msgOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.hugo.wblog.proto.WblogMsgProto.internal_static_wblog_msg_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.hugo.wblog.proto.WblogMsgProto.internal_static_wblog_msg_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.hugo.wblog.proto.WblogMsgProto.wblog_msg.class, com.hugo.wblog.proto.WblogMsgProto.wblog_msg.Builder.class);
      }

      // Construct using com.hugo.wblog.proto.WblogMsgProto.wblog_msg.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        id_ = 0L;

        msgSender_ = "";

        msgReceiver_ = "";

        msgContent_ = "";

        status_ = 0L;

        if (createDateBuilder_ == null) {
          createDate_ = null;
        } else {
          createDate_ = null;
          createDateBuilder_ = null;
        }
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.hugo.wblog.proto.WblogMsgProto.internal_static_wblog_msg_descriptor;
      }

      @java.lang.Override
      public com.hugo.wblog.proto.WblogMsgProto.wblog_msg getDefaultInstanceForType() {
        return com.hugo.wblog.proto.WblogMsgProto.wblog_msg.getDefaultInstance();
      }

      @java.lang.Override
      public com.hugo.wblog.proto.WblogMsgProto.wblog_msg build() {
        com.hugo.wblog.proto.WblogMsgProto.wblog_msg result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.hugo.wblog.proto.WblogMsgProto.wblog_msg buildPartial() {
        com.hugo.wblog.proto.WblogMsgProto.wblog_msg result = new com.hugo.wblog.proto.WblogMsgProto.wblog_msg(this);
        result.id_ = id_;
        result.msgSender_ = msgSender_;
        result.msgReceiver_ = msgReceiver_;
        result.msgContent_ = msgContent_;
        result.status_ = status_;
        if (createDateBuilder_ == null) {
          result.createDate_ = createDate_;
        } else {
          result.createDate_ = createDateBuilder_.build();
        }
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.hugo.wblog.proto.WblogMsgProto.wblog_msg) {
          return mergeFrom((com.hugo.wblog.proto.WblogMsgProto.wblog_msg)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.hugo.wblog.proto.WblogMsgProto.wblog_msg other) {
        if (other == com.hugo.wblog.proto.WblogMsgProto.wblog_msg.getDefaultInstance()) return this;
        if (other.getId() != 0L) {
          setId(other.getId());
        }
        if (!other.getMsgSender().isEmpty()) {
          msgSender_ = other.msgSender_;
          onChanged();
        }
        if (!other.getMsgReceiver().isEmpty()) {
          msgReceiver_ = other.msgReceiver_;
          onChanged();
        }
        if (!other.getMsgContent().isEmpty()) {
          msgContent_ = other.msgContent_;
          onChanged();
        }
        if (other.getStatus() != 0L) {
          setStatus(other.getStatus());
        }
        if (other.hasCreateDate()) {
          mergeCreateDate(other.getCreateDate());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.hugo.wblog.proto.WblogMsgProto.wblog_msg parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.hugo.wblog.proto.WblogMsgProto.wblog_msg) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private long id_ ;
      /**
       * <code>int64 id = 1;</code>
       */
      public long getId() {
        return id_;
      }
      /**
       * <code>int64 id = 1;</code>
       */
      public Builder setId(long value) {
        
        id_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int64 id = 1;</code>
       */
      public Builder clearId() {
        
        id_ = 0L;
        onChanged();
        return this;
      }

      private java.lang.Object msgSender_ = "";
      /**
       * <code>string msgSender = 2;</code>
       */
      public java.lang.String getMsgSender() {
        java.lang.Object ref = msgSender_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          msgSender_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string msgSender = 2;</code>
       */
      public com.google.protobuf.ByteString
          getMsgSenderBytes() {
        java.lang.Object ref = msgSender_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          msgSender_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string msgSender = 2;</code>
       */
      public Builder setMsgSender(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        msgSender_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string msgSender = 2;</code>
       */
      public Builder clearMsgSender() {
        
        msgSender_ = getDefaultInstance().getMsgSender();
        onChanged();
        return this;
      }
      /**
       * <code>string msgSender = 2;</code>
       */
      public Builder setMsgSenderBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        msgSender_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object msgReceiver_ = "";
      /**
       * <code>string msgReceiver = 3;</code>
       */
      public java.lang.String getMsgReceiver() {
        java.lang.Object ref = msgReceiver_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          msgReceiver_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string msgReceiver = 3;</code>
       */
      public com.google.protobuf.ByteString
          getMsgReceiverBytes() {
        java.lang.Object ref = msgReceiver_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          msgReceiver_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string msgReceiver = 3;</code>
       */
      public Builder setMsgReceiver(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        msgReceiver_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string msgReceiver = 3;</code>
       */
      public Builder clearMsgReceiver() {
        
        msgReceiver_ = getDefaultInstance().getMsgReceiver();
        onChanged();
        return this;
      }
      /**
       * <code>string msgReceiver = 3;</code>
       */
      public Builder setMsgReceiverBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        msgReceiver_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object msgContent_ = "";
      /**
       * <code>string msgContent = 4;</code>
       */
      public java.lang.String getMsgContent() {
        java.lang.Object ref = msgContent_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          msgContent_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string msgContent = 4;</code>
       */
      public com.google.protobuf.ByteString
          getMsgContentBytes() {
        java.lang.Object ref = msgContent_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          msgContent_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string msgContent = 4;</code>
       */
      public Builder setMsgContent(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        msgContent_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string msgContent = 4;</code>
       */
      public Builder clearMsgContent() {
        
        msgContent_ = getDefaultInstance().getMsgContent();
        onChanged();
        return this;
      }
      /**
       * <code>string msgContent = 4;</code>
       */
      public Builder setMsgContentBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        msgContent_ = value;
        onChanged();
        return this;
      }

      private long status_ ;
      /**
       * <code>int64 status = 5;</code>
       */
      public long getStatus() {
        return status_;
      }
      /**
       * <code>int64 status = 5;</code>
       */
      public Builder setStatus(long value) {
        
        status_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int64 status = 5;</code>
       */
      public Builder clearStatus() {
        
        status_ = 0L;
        onChanged();
        return this;
      }

      private com.google.protobuf.Timestamp createDate_;
      private com.google.protobuf.SingleFieldBuilderV3<
          com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder> createDateBuilder_;
      /**
       * <code>.google.protobuf.Timestamp createDate = 6;</code>
       */
      public boolean hasCreateDate() {
        return createDateBuilder_ != null || createDate_ != null;
      }
      /**
       * <code>.google.protobuf.Timestamp createDate = 6;</code>
       */
      public com.google.protobuf.Timestamp getCreateDate() {
        if (createDateBuilder_ == null) {
          return createDate_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : createDate_;
        } else {
          return createDateBuilder_.getMessage();
        }
      }
      /**
       * <code>.google.protobuf.Timestamp createDate = 6;</code>
       */
      public Builder setCreateDate(com.google.protobuf.Timestamp value) {
        if (createDateBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          createDate_ = value;
          onChanged();
        } else {
          createDateBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <code>.google.protobuf.Timestamp createDate = 6;</code>
       */
      public Builder setCreateDate(
          com.google.protobuf.Timestamp.Builder builderForValue) {
        if (createDateBuilder_ == null) {
          createDate_ = builderForValue.build();
          onChanged();
        } else {
          createDateBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <code>.google.protobuf.Timestamp createDate = 6;</code>
       */
      public Builder mergeCreateDate(com.google.protobuf.Timestamp value) {
        if (createDateBuilder_ == null) {
          if (createDate_ != null) {
            createDate_ =
              com.google.protobuf.Timestamp.newBuilder(createDate_).mergeFrom(value).buildPartial();
          } else {
            createDate_ = value;
          }
          onChanged();
        } else {
          createDateBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <code>.google.protobuf.Timestamp createDate = 6;</code>
       */
      public Builder clearCreateDate() {
        if (createDateBuilder_ == null) {
          createDate_ = null;
          onChanged();
        } else {
          createDate_ = null;
          createDateBuilder_ = null;
        }

        return this;
      }
      /**
       * <code>.google.protobuf.Timestamp createDate = 6;</code>
       */
      public com.google.protobuf.Timestamp.Builder getCreateDateBuilder() {
        
        onChanged();
        return getCreateDateFieldBuilder().getBuilder();
      }
      /**
       * <code>.google.protobuf.Timestamp createDate = 6;</code>
       */
      public com.google.protobuf.TimestampOrBuilder getCreateDateOrBuilder() {
        if (createDateBuilder_ != null) {
          return createDateBuilder_.getMessageOrBuilder();
        } else {
          return createDate_ == null ?
              com.google.protobuf.Timestamp.getDefaultInstance() : createDate_;
        }
      }
      /**
       * <code>.google.protobuf.Timestamp createDate = 6;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder> 
          getCreateDateFieldBuilder() {
        if (createDateBuilder_ == null) {
          createDateBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder>(
                  getCreateDate(),
                  getParentForChildren(),
                  isClean());
          createDate_ = null;
        }
        return createDateBuilder_;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:wblog_msg)
    }

    // @@protoc_insertion_point(class_scope:wblog_msg)
    private static final com.hugo.wblog.proto.WblogMsgProto.wblog_msg DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.hugo.wblog.proto.WblogMsgProto.wblog_msg();
    }

    public static com.hugo.wblog.proto.WblogMsgProto.wblog_msg getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<wblog_msg>
        PARSER = new com.google.protobuf.AbstractParser<wblog_msg>() {
      @java.lang.Override
      public wblog_msg parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new wblog_msg(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<wblog_msg> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<wblog_msg> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.hugo.wblog.proto.WblogMsgProto.wblog_msg getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_wblog_msg_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_wblog_msg_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\027wblog_msg_content.proto\032\037google/protob" +
      "uf/timestamp.proto\"\223\001\n\twblog_msg\022\n\n\002id\030\001" +
      " \001(\003\022\021\n\tmsgSender\030\002 \001(\t\022\023\n\013msgReceiver\030\003" +
      " \001(\t\022\022\n\nmsgContent\030\004 \001(\t\022\016\n\006status\030\005 \001(\003" +
      "\022.\n\ncreateDate\030\006 \001(\0132\032.google.protobuf.T" +
      "imestampB%\n\024com.hugo.wblog.protoB\rWblogM" +
      "sgProtob\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.google.protobuf.TimestampProto.getDescriptor(),
        });
    internal_static_wblog_msg_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_wblog_msg_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_wblog_msg_descriptor,
        new java.lang.String[] { "Id", "MsgSender", "MsgReceiver", "MsgContent", "Status", "CreateDate", });
    com.google.protobuf.TimestampProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
