// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: comment_content.proto

package com.wblog.proto;

public final class CommentContentProto {
  private CommentContentProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface comment_contentOrBuilder extends
      // @@protoc_insertion_point(interface_extends:comment_content)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>int64 id = 1;</code>
     */
    long getId();

    /**
     * <code>int64 blogId = 2;</code>
     */
    long getBlogId();

    /**
     * <code>string commentContent = 3;</code>
     */
    java.lang.String getCommentContent();
    /**
     * <code>string commentContent = 3;</code>
     */
    com.google.protobuf.ByteString
        getCommentContentBytes();

    /**
     * <code>string commenter = 4;</code>
     */
    java.lang.String getCommenter();
    /**
     * <code>string commenter = 4;</code>
     */
    com.google.protobuf.ByteString
        getCommenterBytes();

    /**
     * <code>.google.protobuf.Timestamp createDate = 5;</code>
     */
    boolean hasCreateDate();
    /**
     * <code>.google.protobuf.Timestamp createDate = 5;</code>
     */
    com.google.protobuf.Timestamp getCreateDate();
    /**
     * <code>.google.protobuf.Timestamp createDate = 5;</code>
     */
    com.google.protobuf.TimestampOrBuilder getCreateDateOrBuilder();
  }
  /**
   * Protobuf type {@code comment_content}
   */
  public  static final class comment_content extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:comment_content)
      comment_contentOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use comment_content.newBuilder() to construct.
    private comment_content(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private comment_content() {
      commentContent_ = "";
      commenter_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new comment_content();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private comment_content(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {

              id_ = input.readInt64();
              break;
            }
            case 16: {

              blogId_ = input.readInt64();
              break;
            }
            case 26: {
              java.lang.String s = input.readStringRequireUtf8();

              commentContent_ = s;
              break;
            }
            case 34: {
              java.lang.String s = input.readStringRequireUtf8();

              commenter_ = s;
              break;
            }
            case 42: {
              com.google.protobuf.Timestamp.Builder subBuilder = null;
              if (createDate_ != null) {
                subBuilder = createDate_.toBuilder();
              }
              createDate_ = input.readMessage(com.google.protobuf.Timestamp.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(createDate_);
                createDate_ = subBuilder.buildPartial();
              }

              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.wblog.proto.CommentContentProto.internal_static_comment_content_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.wblog.proto.CommentContentProto.internal_static_comment_content_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.wblog.proto.CommentContentProto.comment_content.class, com.wblog.proto.CommentContentProto.comment_content.Builder.class);
    }

    public static final int ID_FIELD_NUMBER = 1;
    private long id_;
    /**
     * <code>int64 id = 1;</code>
     */
    public long getId() {
      return id_;
    }

    public static final int BLOGID_FIELD_NUMBER = 2;
    private long blogId_;
    /**
     * <code>int64 blogId = 2;</code>
     */
    public long getBlogId() {
      return blogId_;
    }

    public static final int COMMENTCONTENT_FIELD_NUMBER = 3;
    private volatile java.lang.Object commentContent_;
    /**
     * <code>string commentContent = 3;</code>
     */
    public java.lang.String getCommentContent() {
      java.lang.Object ref = commentContent_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        commentContent_ = s;
        return s;
      }
    }
    /**
     * <code>string commentContent = 3;</code>
     */
    public com.google.protobuf.ByteString
        getCommentContentBytes() {
      java.lang.Object ref = commentContent_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        commentContent_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int COMMENTER_FIELD_NUMBER = 4;
    private volatile java.lang.Object commenter_;
    /**
     * <code>string commenter = 4;</code>
     */
    public java.lang.String getCommenter() {
      java.lang.Object ref = commenter_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        commenter_ = s;
        return s;
      }
    }
    /**
     * <code>string commenter = 4;</code>
     */
    public com.google.protobuf.ByteString
        getCommenterBytes() {
      java.lang.Object ref = commenter_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        commenter_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int CREATEDATE_FIELD_NUMBER = 5;
    private com.google.protobuf.Timestamp createDate_;
    /**
     * <code>.google.protobuf.Timestamp createDate = 5;</code>
     */
    public boolean hasCreateDate() {
      return createDate_ != null;
    }
    /**
     * <code>.google.protobuf.Timestamp createDate = 5;</code>
     */
    public com.google.protobuf.Timestamp getCreateDate() {
      return createDate_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : createDate_;
    }
    /**
     * <code>.google.protobuf.Timestamp createDate = 5;</code>
     */
    public com.google.protobuf.TimestampOrBuilder getCreateDateOrBuilder() {
      return getCreateDate();
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (id_ != 0L) {
        output.writeInt64(1, id_);
      }
      if (blogId_ != 0L) {
        output.writeInt64(2, blogId_);
      }
      if (!getCommentContentBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, commentContent_);
      }
      if (!getCommenterBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 4, commenter_);
      }
      if (createDate_ != null) {
        output.writeMessage(5, getCreateDate());
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (id_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(1, id_);
      }
      if (blogId_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(2, blogId_);
      }
      if (!getCommentContentBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, commentContent_);
      }
      if (!getCommenterBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, commenter_);
      }
      if (createDate_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(5, getCreateDate());
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.wblog.proto.CommentContentProto.comment_content)) {
        return super.equals(obj);
      }
      com.wblog.proto.CommentContentProto.comment_content other = (com.wblog.proto.CommentContentProto.comment_content) obj;

      if (getId()
          != other.getId()) return false;
      if (getBlogId()
          != other.getBlogId()) return false;
      if (!getCommentContent()
          .equals(other.getCommentContent())) return false;
      if (!getCommenter()
          .equals(other.getCommenter())) return false;
      if (hasCreateDate() != other.hasCreateDate()) return false;
      if (hasCreateDate()) {
        if (!getCreateDate()
            .equals(other.getCreateDate())) return false;
      }
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + ID_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getId());
      hash = (37 * hash) + BLOGID_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getBlogId());
      hash = (37 * hash) + COMMENTCONTENT_FIELD_NUMBER;
      hash = (53 * hash) + getCommentContent().hashCode();
      hash = (37 * hash) + COMMENTER_FIELD_NUMBER;
      hash = (53 * hash) + getCommenter().hashCode();
      if (hasCreateDate()) {
        hash = (37 * hash) + CREATEDATE_FIELD_NUMBER;
        hash = (53 * hash) + getCreateDate().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.wblog.proto.CommentContentProto.comment_content parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.wblog.proto.CommentContentProto.comment_content parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.wblog.proto.CommentContentProto.comment_content parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.wblog.proto.CommentContentProto.comment_content parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.wblog.proto.CommentContentProto.comment_content parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.wblog.proto.CommentContentProto.comment_content parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.wblog.proto.CommentContentProto.comment_content parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.wblog.proto.CommentContentProto.comment_content parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.wblog.proto.CommentContentProto.comment_content parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.wblog.proto.CommentContentProto.comment_content parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.wblog.proto.CommentContentProto.comment_content parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.wblog.proto.CommentContentProto.comment_content parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.wblog.proto.CommentContentProto.comment_content prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code comment_content}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:comment_content)
        com.wblog.proto.CommentContentProto.comment_contentOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.wblog.proto.CommentContentProto.internal_static_comment_content_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.wblog.proto.CommentContentProto.internal_static_comment_content_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.wblog.proto.CommentContentProto.comment_content.class, com.wblog.proto.CommentContentProto.comment_content.Builder.class);
      }

      // Construct using com.wblog.proto.CommentContentProto.comment_content.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        id_ = 0L;

        blogId_ = 0L;

        commentContent_ = "";

        commenter_ = "";

        if (createDateBuilder_ == null) {
          createDate_ = null;
        } else {
          createDate_ = null;
          createDateBuilder_ = null;
        }
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.wblog.proto.CommentContentProto.internal_static_comment_content_descriptor;
      }

      @java.lang.Override
      public com.wblog.proto.CommentContentProto.comment_content getDefaultInstanceForType() {
        return com.wblog.proto.CommentContentProto.comment_content.getDefaultInstance();
      }

      @java.lang.Override
      public com.wblog.proto.CommentContentProto.comment_content build() {
        com.wblog.proto.CommentContentProto.comment_content result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.wblog.proto.CommentContentProto.comment_content buildPartial() {
        com.wblog.proto.CommentContentProto.comment_content result = new com.wblog.proto.CommentContentProto.comment_content(this);
        result.id_ = id_;
        result.blogId_ = blogId_;
        result.commentContent_ = commentContent_;
        result.commenter_ = commenter_;
        if (createDateBuilder_ == null) {
          result.createDate_ = createDate_;
        } else {
          result.createDate_ = createDateBuilder_.build();
        }
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.wblog.proto.CommentContentProto.comment_content) {
          return mergeFrom((com.wblog.proto.CommentContentProto.comment_content)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.wblog.proto.CommentContentProto.comment_content other) {
        if (other == com.wblog.proto.CommentContentProto.comment_content.getDefaultInstance()) return this;
        if (other.getId() != 0L) {
          setId(other.getId());
        }
        if (other.getBlogId() != 0L) {
          setBlogId(other.getBlogId());
        }
        if (!other.getCommentContent().isEmpty()) {
          commentContent_ = other.commentContent_;
          onChanged();
        }
        if (!other.getCommenter().isEmpty()) {
          commenter_ = other.commenter_;
          onChanged();
        }
        if (other.hasCreateDate()) {
          mergeCreateDate(other.getCreateDate());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.wblog.proto.CommentContentProto.comment_content parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.wblog.proto.CommentContentProto.comment_content) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private long id_ ;
      /**
       * <code>int64 id = 1;</code>
       */
      public long getId() {
        return id_;
      }
      /**
       * <code>int64 id = 1;</code>
       */
      public Builder setId(long value) {
        
        id_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int64 id = 1;</code>
       */
      public Builder clearId() {
        
        id_ = 0L;
        onChanged();
        return this;
      }

      private long blogId_ ;
      /**
       * <code>int64 blogId = 2;</code>
       */
      public long getBlogId() {
        return blogId_;
      }
      /**
       * <code>int64 blogId = 2;</code>
       */
      public Builder setBlogId(long value) {
        
        blogId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int64 blogId = 2;</code>
       */
      public Builder clearBlogId() {
        
        blogId_ = 0L;
        onChanged();
        return this;
      }

      private java.lang.Object commentContent_ = "";
      /**
       * <code>string commentContent = 3;</code>
       */
      public java.lang.String getCommentContent() {
        java.lang.Object ref = commentContent_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          commentContent_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string commentContent = 3;</code>
       */
      public com.google.protobuf.ByteString
          getCommentContentBytes() {
        java.lang.Object ref = commentContent_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          commentContent_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string commentContent = 3;</code>
       */
      public Builder setCommentContent(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        commentContent_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string commentContent = 3;</code>
       */
      public Builder clearCommentContent() {
        
        commentContent_ = getDefaultInstance().getCommentContent();
        onChanged();
        return this;
      }
      /**
       * <code>string commentContent = 3;</code>
       */
      public Builder setCommentContentBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        commentContent_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object commenter_ = "";
      /**
       * <code>string commenter = 4;</code>
       */
      public java.lang.String getCommenter() {
        java.lang.Object ref = commenter_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          commenter_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string commenter = 4;</code>
       */
      public com.google.protobuf.ByteString
          getCommenterBytes() {
        java.lang.Object ref = commenter_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          commenter_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string commenter = 4;</code>
       */
      public Builder setCommenter(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        commenter_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string commenter = 4;</code>
       */
      public Builder clearCommenter() {
        
        commenter_ = getDefaultInstance().getCommenter();
        onChanged();
        return this;
      }
      /**
       * <code>string commenter = 4;</code>
       */
      public Builder setCommenterBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        commenter_ = value;
        onChanged();
        return this;
      }

      private com.google.protobuf.Timestamp createDate_;
      private com.google.protobuf.SingleFieldBuilderV3<
          com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder> createDateBuilder_;
      /**
       * <code>.google.protobuf.Timestamp createDate = 5;</code>
       */
      public boolean hasCreateDate() {
        return createDateBuilder_ != null || createDate_ != null;
      }
      /**
       * <code>.google.protobuf.Timestamp createDate = 5;</code>
       */
      public com.google.protobuf.Timestamp getCreateDate() {
        if (createDateBuilder_ == null) {
          return createDate_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : createDate_;
        } else {
          return createDateBuilder_.getMessage();
        }
      }
      /**
       * <code>.google.protobuf.Timestamp createDate = 5;</code>
       */
      public Builder setCreateDate(com.google.protobuf.Timestamp value) {
        if (createDateBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          createDate_ = value;
          onChanged();
        } else {
          createDateBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <code>.google.protobuf.Timestamp createDate = 5;</code>
       */
      public Builder setCreateDate(
          com.google.protobuf.Timestamp.Builder builderForValue) {
        if (createDateBuilder_ == null) {
          createDate_ = builderForValue.build();
          onChanged();
        } else {
          createDateBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <code>.google.protobuf.Timestamp createDate = 5;</code>
       */
      public Builder mergeCreateDate(com.google.protobuf.Timestamp value) {
        if (createDateBuilder_ == null) {
          if (createDate_ != null) {
            createDate_ =
              com.google.protobuf.Timestamp.newBuilder(createDate_).mergeFrom(value).buildPartial();
          } else {
            createDate_ = value;
          }
          onChanged();
        } else {
          createDateBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <code>.google.protobuf.Timestamp createDate = 5;</code>
       */
      public Builder clearCreateDate() {
        if (createDateBuilder_ == null) {
          createDate_ = null;
          onChanged();
        } else {
          createDate_ = null;
          createDateBuilder_ = null;
        }

        return this;
      }
      /**
       * <code>.google.protobuf.Timestamp createDate = 5;</code>
       */
      public com.google.protobuf.Timestamp.Builder getCreateDateBuilder() {
        
        onChanged();
        return getCreateDateFieldBuilder().getBuilder();
      }
      /**
       * <code>.google.protobuf.Timestamp createDate = 5;</code>
       */
      public com.google.protobuf.TimestampOrBuilder getCreateDateOrBuilder() {
        if (createDateBuilder_ != null) {
          return createDateBuilder_.getMessageOrBuilder();
        } else {
          return createDate_ == null ?
              com.google.protobuf.Timestamp.getDefaultInstance() : createDate_;
        }
      }
      /**
       * <code>.google.protobuf.Timestamp createDate = 5;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder> 
          getCreateDateFieldBuilder() {
        if (createDateBuilder_ == null) {
          createDateBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder>(
                  getCreateDate(),
                  getParentForChildren(),
                  isClean());
          createDate_ = null;
        }
        return createDateBuilder_;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:comment_content)
    }

    // @@protoc_insertion_point(class_scope:comment_content)
    private static final com.wblog.proto.CommentContentProto.comment_content DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.wblog.proto.CommentContentProto.comment_content();
    }

    public static com.wblog.proto.CommentContentProto.comment_content getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<comment_content>
        PARSER = new com.google.protobuf.AbstractParser<comment_content>() {
      @java.lang.Override
      public comment_content parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new comment_content(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<comment_content> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<comment_content> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.wblog.proto.CommentContentProto.comment_content getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_comment_content_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_comment_content_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\025comment_content.proto\032\037google/protobuf" +
      "/timestamp.proto\"\210\001\n\017comment_content\022\n\n\002" +
      "id\030\001 \001(\003\022\016\n\006blogId\030\002 \001(\003\022\026\n\016commentConte" +
      "nt\030\003 \001(\t\022\021\n\tcommenter\030\004 \001(\t\022.\n\ncreateDat" +
      "e\030\005 \001(\0132\032.google.protobuf.TimestampB&\n\017c" +
      "om.wblog.protoB\023CommentContentProtob\006pro" +
      "to3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.google.protobuf.TimestampProto.getDescriptor(),
        });
    internal_static_comment_content_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_comment_content_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_comment_content_descriptor,
        new java.lang.String[] { "Id", "BlogId", "CommentContent", "Commenter", "CreateDate", });
    com.google.protobuf.TimestampProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
